# Generated by Django 2.2.7 on 2019-11-26 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(default='This is Default Text')),
                ('pubdate', models.DateTimeField(default=datetime.datetime(2019, 11, 26, 15, 50, 22, 908388, tzinfo=utc))),
            ],
        ),
    ]
