# Generated by Django 2.2.7 on 2019-11-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20191126_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='myimage',
            field=models.ImageField(null=True, upload_to='mages/'),
        ),
    ]
