# Generated by Django 2.2.7 on 2019-12-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_myimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='myimage',
        ),
    ]
